name: Build documentation

on:
  push:

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make build/ folder
        run: mkdir ./build && cp -r addons/sxgd/doc/* ./build
      - name: Build documentation
        uses: tonynv/asciidoctor-action@master
        with:
          program: "cd ./build && asciidoctor index.adoc"
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build