name: Build documentation

on:
  push:

jobs:
  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build .adoc files from XML
        run: cd doc && python tools/build_xml_adoc.py --all
      - name: Install Asciidoctor
        run: sudo gem install asciidoctor
      - name: Build documentation
        run: cd doc && asciidoctor index.adoc
      - name: Cleanup
        run: rm -rf doc/classes_xml doc/tools doc/.gitignore doc/.gdignore doc/class.xsd && find . -name "*.adoc" -delete
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: doc